# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Kochanek Design
email: kyle@kylekochanek.com
description: A Product Designer living in Dayton OH. with mad UI & UX Skills.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

# Logo settings
logo-image-url: images/logo.svg
font-awesome-icon-logo:

# Social settings
github_username: kocheck
twitter_username: kyle_kochanek
facebook_URL: https://facebook.com/kylekochanek
dribbble_username: kyle_kochanek

# Build settings
markdown: kramdown

# Layout settings
home-link-in-menu: yes
