# Welcome to Jekyll!
#

# Site settings
title: Kochanek Design
description: Hardworking Product Designer raised in the south currently living in Dayton OH.
Currently a Senior Product Designer at Momentum, I mostly play in sketch (app) and photoshop when not in my sketchbook planning out my next app.
owner: Kyle Kochanek # or company name
first_published: 2017 # if migrating another site, the year of your first publish
email: kyle@kylekochanek.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/kyle_kochanek
  github: https://github.com/kocheck
  linkedin-square: https://linkedin.com/in/kylekochanek
  facebook-official: https://facebook.com/kylekochanek
  #google-plus-square: https://plus.google.com/u/0/+<username>
  email: /contact/
  dribbble: https://dribbble.com/kyle_kochanek
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
